api_platform:
    title: 'Sécurité des applications API REST'
    description: 'Bienvenue sur API Platform pour le TP : sécurité des applications.'
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
